#Lab 3: PCR and PLS Regression

```{r}
library(pls)
library(ISLR)
Hitters <- na.omit(Hitters)
x <- model.matrix(Salary∼.,data = Hitters)[,-1]
y <- Hitters$Salary
set.seed(2)
pcr.fit <- pcr(Salary~., data = Hitters, scale = TRUE, Validation = "CV")
summary(pcr.fit)
validationplot(pcr.fit,val.type = "MSEP")
```
Perform PCR on training data and evaluate performance on testing data set.
```{r}
set.seed(1)
train <- sample(1:nrow(x), nrow(x)/2)
test <- (-train)
y.test <- y[test]
pcr.fit <- pcr(Salary∼., data=Hitters ,subset=train,scale=TRUE, validation="CV") 
validationplot(pcr.fit ,val.type="MSEP")
```
```{r}
pcr.pred <- predict(pcr.fit,x[test,],ncomp=7)
mean((pcr.pred-y.test)^2)
```
Results in a similiar MSE as ridge regression and lasso.
```{r}
pcr.fit <- pcr(y~x,scale=TRUE,ncomp=7)
summary(pcr.fit)
```
#Partial Least Squares
```{r}
set.seed(1)
pls.fit <- plsr(Salary~., data = Hitters,subset=train,scale=TRUE,validation="CV")
summary(pls.fit)
```
Calculate the MSE M = 2.
```{r}
pls.pred <- predict(pls.fit,x[test,],ncomp=2)
mean((pls.pred-y.test)^2)
```
This test MSE is slightly higher than the test MSE from ridge regression, lasso, and PCR.
```{r}
pls.fit <- plsr(Salary~., data = Hitters, scale = TRUE, ncomp = 2)
summary(pls.fit)
```

